heat_template_version: 2014-10-16

description: deploy security-group.

parameters:
  name:
    description: name of vpc
    type: string
    default: name os sg

resources:
  sg:
    type: OS::Neutron::SecurityGroup
    properties:
        description: String
        name: { get_param: name }
        rules: [{port_range_max: 22, port_range_min: 22, protocol: tcp, direction: ingress},
        {port_range_max: 80, port_range_min: 80, protocol: tcp, direction: ingress},
        {port_range_max: 8080, port_range_min: 8080, protocol: tcp, direction: ingress},
        {protocol: icmp, direction: ingress}]

outputs:
  sg_id:
    description: id of security group.
    value: { get_resource: sg }
